apiVersion: v1
kind: Service
metadata:
  name: atlas-api
  namespace: atlas
  labels:
    app.kubernetes.io/name: atlas-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: atlas-bos
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atlas-api
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP