apiVersion: v1
kind: Service
metadata:
  name: atlas-worker
  namespace: atlas
  labels:
    app.kubernetes.io/name: atlas-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: atlas-bos
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atlas-worker
  ports:
    - name: http
      port: 3002
      targetPort: http
      protocol: TCP