global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: atlas-api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3001', 'host.docker.internal:3001']

  - job_name: atlas-worker
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:3002', 'host.docker.internal:3002']